name: opera-utils-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - click>=7.0
  - h5py>=1.10
  - numpy>=1.20
  - pooch>=1.7
  - pyproj>=3.3
  - shapely>=1.8
  - typing_extensions>=4
