name: opera-utils-env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.3
  - git
  - h5py>=1.10
  - numpy>=1.20
  - pooch>=1.7
  - pyproj>=3.3
  - shapely>=1.8
  - typing_extensions>=4
  - tyro>=0.9
  - asf_search>=6.7
  - gdal>=3.7
  - libgdal-netcdf
  - rasterio>=1.3
  - affine
  - botocore
  - aiohttp
  - fsspec
  - h5netcdf
  - s3fs
  - tqdm
  - dask
  - zarr
